name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  paths-ignore:
  - "docs/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: npm install -g truffle
    - run: truffle test
