name: CI

on:
  push:
    branches: [ master ]
    paths-ignore: [ "docs/**" ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
    - run: npm install -g truffle
    - run: truffle test
